name: Student CI Pipeline
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download repository code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm test
  deploy:
      needs: build-and-test
      runs-on: ubuntu-latest

      steps:
        - name: Deploy to EC2 via SSH
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ec2-user
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              cd ~/your-project-folder
              git pull origin main
              npm install
              pm2 restart all